### ISSUE TITLE
Don't include core-js

### ISSUE THREAD

**Issue by pixeldrew** [shendepu/nashorn-polyfill#3]
\Wondering if you can include a build that doesn't have core-js. Babel already includes these polly's as part of babel-runtime.

The only thing needed would be to get Nashorn up to es5 compliance.

**Comment by shendepu** [comment]
In theory babel polyfill should be enough, but in reality it is not. I tried not including core-js but with babel-polyfill in react app, but it always throws errors like some of method of Array is missing, and it's very difficult to debug on Nashorn with manual logging. 

Definitely there is still room for improvement to include minimum polyfill from core-js, but it requires big amount of time on test it. 

And you may customize it by yourself, the build anyway need to be put on JVM server.
